/*
 * tp-voip-engine.c - Source for TpVoipEngine
 * Copyright (C) 2005 Collabora Ltd.
 * Copyright (C) 2005 Nokia Corporation
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <dbus/dbus-glib.h>
#include <stdio.h>
#include <stdlib.h>

#include "tp-voip-engine.h"
#include "tp-voip-engine-signals-marshal.h"

#include "tp-voip-engine-glue.h"

#include "common/telepathy-constants.h"
#include "common/telepathy-errors.h"
#include "common/telepathy-errors-enumtypes.h"

#define BUS_NAME        "org.freedesktop.Telepathy.VoipEngine"
#define OBJECT_PATH     "/org/freedesktop/Telepathy/VoipEngine"

static gboolean handling_channel = FALSE;

G_DEFINE_TYPE(TpVoipEngine, tp_voip_engine, G_TYPE_OBJECT)

/* private structure */
typedef struct _TpVoipEnginePrivate TpVoipEnginePrivate;

struct _TpVoipEnginePrivate
{
  gboolean dispose_has_run;
};

#define TP_VOIP_ENGINE_GET_PRIVATE(o)     (G_TYPE_INSTANCE_GET_PRIVATE ((o), TP_TYPE_VOIP_ENGINE, TpVoipEnginePrivate))

static void
tp_voip_engine_init (TpVoipEngine *obj)
{
  TpVoipEnginePrivate *priv = TP_VOIP_ENGINE_GET_PRIVATE (obj);

  /* allocate any data required by the object here */
  /* this line allows the plain autogenerated code to compile with -Werror
     remove it!*/
  g_assert(priv);
}

static void tp_voip_engine_dispose (GObject *object);
static void tp_voip_engine_finalize (GObject *object);

static void
tp_voip_engine_class_init (TpVoipEngineClass *tp_voip_engine_class)
{
  GObjectClass *object_class = G_OBJECT_CLASS (tp_voip_engine_class);

  g_type_class_add_private (tp_voip_engine_class, sizeof (TpVoipEnginePrivate));

  object_class->dispose = tp_voip_engine_dispose;
  object_class->finalize = tp_voip_engine_finalize;

  dbus_g_object_type_install_info (G_TYPE_FROM_CLASS (tp_voip_engine_class), &dbus_glib_tp_voip_engine_object_info);
}

void
tp_voip_engine_dispose (GObject *object)
{
  TpVoipEngine *self = TP_VOIP_ENGINE (object);
  TpVoipEnginePrivate *priv = TP_VOIP_ENGINE_GET_PRIVATE (self);

  if (priv->dispose_has_run)
    return;

  priv->dispose_has_run = TRUE;

  /* release any references held by the object here */

  if (G_OBJECT_CLASS (tp_voip_engine_parent_class)->dispose)
    G_OBJECT_CLASS (tp_voip_engine_parent_class)->dispose (object);
}

void
tp_voip_engine_finalize (GObject *object)
{
  TpVoipEngine *self = TP_VOIP_ENGINE (object);
  TpVoipEnginePrivate *priv = TP_VOIP_ENGINE_GET_PRIVATE (self);

  /* free any data held directly by the object here */
  /* this line allows the plain autogenerated code to compile with -Werror
     remove it!*/
  g_assert(priv);

  G_OBJECT_CLASS (tp_voip_engine_parent_class)->finalize (object);
}



/**
 * tp_voip_engine_handle_channel
 *
 * Implements DBus method HandleChannel
 * on interface org.freedesktop.Telepathy.ChannelHandler
 *
 * @error: Used to return a pointer to a GError detailing any error
 *         that occured, DBus will throw the error only if this
 *         function returns false.
 *
 * Returns: TRUE if successful, FALSE if an error was thrown.
 */
gboolean tp_voip_engine_handle_channel (TpVoipEngine *obj, const gchar * bus_name, const gchar * connection, const gchar * channel_type, const gchar * channel, guint handle_type, guint handle, GError **error)
{
  if (handling_channel)
    {
      *error = g_error_new (TELEPATHY_ERRORS, NotAvailable,
                            "VoIP Engine is already handling a channel");

      return FALSE;
    }
  return TRUE;
}

DBusGConnection *
get_bus ()
{
  static DBusGConnection *bus = NULL;

  if (bus == NULL)
    {
      GError *error = NULL;

      bus = dbus_g_bus_get (DBUS_BUS_STARTER, &error);

      if (bus == NULL)
        g_error ("Failed to connect to starter bus: %s", error->message);
    }

  return bus;
}

DBusGProxy *
get_bus_proxy ()
{
  static DBusGProxy *bus_proxy = NULL;

  if (bus_proxy == NULL)
    {
      DBusGConnection *bus = get_bus ();

      bus_proxy = dbus_g_proxy_new_for_name (bus,
                                            "org.freedesktop.DBus",
                                            "/org/freedesktop/DBus",
                                            "org.freedesktop.DBus");

      if (bus_proxy == NULL)
        g_error ("Failed to get proxy object for bus.");
    }

  return bus_proxy;
}

void
_tp_voip_engine_register (TpVoipEngine *self)
{
  DBusGConnection *bus;
  DBusGProxy *bus_proxy;
  GError *error = NULL;
  guint request_name_result;

  g_assert (TP_IS_VOIP_ENGINE(self));

  bus = get_bus ();
  bus_proxy = get_bus_proxy ();

  if (!dbus_g_proxy_call (bus_proxy, "RequestName", &error,
                          G_TYPE_STRING, BUS_NAME,
                          G_TYPE_UINT, DBUS_NAME_FLAG_DO_NOT_QUEUE,
                          G_TYPE_INVALID,
                          G_TYPE_UINT, &request_name_result,
                          G_TYPE_INVALID))
    g_error ("Failed to request bus name: %s", error->message);

  if (request_name_result == DBUS_REQUEST_NAME_REPLY_EXISTS)
    g_error ("Failed to acquire bus name, voip engine already running?");

  dbus_g_connection_register_g_object (bus, OBJECT_PATH, G_OBJECT (self));
}


int main(int argc, char **argv) {
  TpVoipEngine *voip_engine;
  GMainLoop *mainloop;

  g_type_init();

  {
    GLogLevelFlags fatal_mask;

    fatal_mask = g_log_set_always_fatal (G_LOG_FATAL_MASK);
    fatal_mask |= G_LOG_LEVEL_CRITICAL;
    g_log_set_always_fatal (fatal_mask);
  }

  g_set_prgname("telepathy-voip-engine");

  mainloop = g_main_loop_new (NULL, FALSE);

  dbus_g_error_domain_register (TELEPATHY_ERRORS, NULL, TELEPATHY_TYPE_ERRORS);

  voip_engine = g_object_new (TP_TYPE_VOIP_ENGINE, NULL);

  _tp_voip_engine_register (voip_engine);

  g_debug("started");

  g_main_loop_run (mainloop);

  return 0;
}
