#ifndef __TYPES_H__
#define __TYPES_H__

#include <telepathy-glib/gtypes.h>

#define TP_TYPE_TRANSPORT_STRUCT \
  TP_STRUCT_TYPE_MEDIA_STREAM_HANDLER_TRANSPORT

#define TP_TYPE_TRANSPORT_LIST \
  TP_ARRAY_TYPE_MEDIA_STREAM_HANDLER_TRANSPORT_LIST

#define TP_TYPE_CANDIDATE_STRUCT \
  TP_STRUCT_TYPE_MEDIA_STREAM_HANDLER_CANDIDATE

#define TP_TYPE_CANDIDATE_LIST \
  TP_ARRAY_TYPE_MEDIA_STREAM_HANDLER_CANDIDATE_LIST

#define TP_TYPE_CODEC_STRUCT \
  TP_STRUCT_TYPE_MEDIA_STREAM_HANDLER_CODEC

#define TP_TYPE_CODEC_LIST \
  TP_ARRAY_TYPE_MEDIA_STREAM_HANDLER_CODEC_LIST

#define TP_TYPE_PROPERTY_DESCRIPTION \
  TP_STRUCT_TYPE_PROPERTY_SPEC

#endif /* __TYPES_H__ */

